name: Backend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Use Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader punkt
        python -m nltk.downloader stopwords
    - run: python -m unittest discover
